export const TOPSTORIES = 'topstories'
export const NEWSTORIES = 'newstories'
export const BESTSTORIES = 'beststories'
export const ASKSTORIES = 'askstories'
export const SHOWSTORIES = 'showstories'
export const JOBSTORIES = 'jobstories'
